# Site settings
title: autohaus collision
email: autohaus_suffern@msn.com
description: >- # this means to ignore newlines until "baseurl:"
  Professional auto body repair, collision restoration, and custom paint services. 
  Quality craftsmanship and exceptional customer service for over 20 years.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://autohauscollisioncenter.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Permalink settings - removes .html extension
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Business Information
business:
  name: "Autohaus Collision Center Inc."
  name_short: "Autohaus"
  tagline: "COLLISION CENTER INC."

  # Contact Information
  phone: "845-358-1770"
  phone_formatted: "(845) 358-1770"
  phone_link: "tel:845-358-1770"
  email: "autohaus_suffern@msn.com"

  # Location
  address:
    street: "12 Wayne Ave"
    city: "Suffern"
    state: "NY"
    zip: "10901"
    full: "12 Wayne Ave, Suffern, NY 10901"

  # Maps & Directions
  google_maps_url: "https://www.google.com/maps/place/12+Wayne+Ave,+Suffern,+NY+10901"

  # Business Hours
  hours:
    weekday: "Mon-Fri: 8AM-5PM"
    weekend: "Closed"
    emergency: "24/7 Emergency Service Available"

  # Social Proof
  years_experience: "25+"
  founded_year: "1998"

# Navigation
header_pages:
  - services.md
  - about.md
  - contact.md

# Optional settings
show_excerpts: false
